[package]
name = "heic-converter"
version = "0.3.0"
description = "一款基于 Tauri 2 和 Vue 3 构建的轻量级跨平台 HEIC 图片转换工具。它可以将 HEIC/HEIF 格式的高清图片快速转换为通用的 JPG 或 PNG 格式。"
authors = ["hotime"]
edition = "2021"

[lib]
name = "heic_converter_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.5.0"
tauri-plugin-fs = "2.4.5"
tauri-plugin-shell = "2.3.4"
image = { version = "0.25.9", features = ["jpeg", "png", "webp"] }
libheif-rs = { version = "2.5.2", default-features = false, features = ["v1_18"] }
thiserror = "2.0.17"
tauri-plugin-log = "2.8.0"
tracing = "0.1"
rayon = "1.10"
turbojpeg = { version = "0.5", features = ["image"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
incremental = false

[profile.release.package."*"]
opt-level = 3
